const products = [
  {
    id: 0,
    img: "./imgs/products/mian.png",
    imgDetail: "./imgs/products/detail/mian.png",
    marca: "Rumapets",
    tipo: "Rascador",
    modelo: "Mian Alfombra",
    model_image: "./imgs/products/detail/text/mian.png",
    price: 4100,
    link: "https://www.rumapets.com.ar/rascadores-chicos/rascador-mian",
    detail:
      "Tubo de 45cm de largo y 12cm de diámetro de madera maciza, forrado en alfombra de 3mm de espesor. Forrado íntegramente en tela de polar soft super suave. Base de 40x40cms. Plataforma de descanso superior rellena de 40x35cms y respaldo de 8,5cms de alto. 2 pompones de juguete con cascabel para incentivar el instinto felino. Terminaciones redondeadas en todas las piezas para mayor seguridad y una estética agradable. Peso total aproximado: 6kg. Medidas totales aproximadas: 55x40x40cms.",
    height: "55cm",
    width: "40cm",
    depth: "40cm",
    weight: "6kg",
    material_de_tubos: "alfombra",
    material_de_estructura: "polar soft",
    stock: 10,
    advice:
      "Trabajamos a pedido; el tiempo de demora es de 3 semanas aproximadamente. En caso de terminar antes el producto se coordina retiro o entrega. Corroborar stock de colores y materiales. Trabajamos con mensajería privada para entregas dentro de CABA y GBA. Podes consultar costos por nuestros canales de atención. Podes retirar por Caballito en los horarios establecidos (no es local a la calle)",
  },
  {
    id: 1,
    img: "./imgs/products/grecia.png",
    imgDetail: "./imgs/products/detail/grecia.png",
    marca: "Rumapets",
    tipo: "Rascador",
    modelo: "Grecia",
    model_image: "./imgs/products/detail/text/grecia.png",
    price: 4560,
    link: "https://www.rumapets.com.ar/rascadores-chicos/rascador-grecia",
    detail:
      "Tubo deTubo de 45cm de largo y 12cm de diámetro de madera maciza, forrado en yute o sisal de 5 o 6mm de espesor. Forrado íntegramente en tela de polar Soft super suave. Base con ornamento de 30x30cms. Plataforma de descanso superior rellena de 30x30cms. 1 pompón de juguete triple con cascabel para incentivar el instinto felino. Terminaciones redondeadas en todas las piezas para mayor seguridad y una estética agradable. Peso total aproximado: 4,5kg. Medidas totales aproximadas: 50x30x30cms.",
    height: "50cm",
    width: "30cm",
    depth: "30cm",
    weight: "4.5kg",
    material_de_tubos: "yute",
    material_de_estructura: "polar soft",
    stock: 5,
    advice:
      "Trabajamos a pedido; el tiempo de demora es de 3 semanas aproximadamente. En caso de terminar antes el producto se coordina retiro o entrega. Corroborar stock de colores y materiales. Trabajamos con mensajería privada para entregas dentro de CABA y GBA. Podes consultar costos por nuestros canales de atención. Podes retirar por Caballito en los horarios establecidos (no es local a la calle)",
  },
  {
    id: 2,
    img: "./imgs/products/mianyute.png",
    imgDetail: "./imgs/products/detail/mianyute.png",
    marca: "Rumapets",
    tipo: "Rascador",
    modelo: "Mian Yute",
    model_image: "./imgs/products/detail/text/mianyute.png",
    price: 5100,
    link: "https://www.rumapets.com.ar/rascadores-chicos/rascador-mian-yute-sisal",
    detail:
      "Tubo de Tubo de 45cm de largo y 12cm de diámetro de madera maciza, forrado en yute o sisal de 5 o 6mm de espesor. Forrado íntegramente en tela de polar Soft super suave. Base de 40x40cms. Plataforma de descanso superior rellena de 40x35cms y respaldo de 8,5xcms de alto. 2 pompones de juguete con cascabel para incentivar el instinto felino. Terminaciones redondeadas en todas las piezas para mayor seguridad y una estética agradable. Peso total aproximado: 8kg. Medidas totales aproximadas: 55x40x40cms.",
    height: "55cm",
    width: "40cm",
    depth: "40cm",
    weight: "8kg",
    material_de_tubos: "yute",
    material_de_estructura: "polar soft",
    stock: 8,
    advice:
      "Trabajamos a pedido; el tiempo de demora es de 3 semanas aproximadamente. En caso de terminar antes el producto se coordina retiro o entrega. Corroborar stock de colores y materiales. Trabajamos con mensajería privada para entregas dentro de CABA y GBA. Podes consultar costos por nuestros canales de atención. Podes retirar por Caballito en los horarios establecidos (no es local a la calle)",
  },
  {
    id: 3,
    img: "./imgs/products/ivy.png",
    imgDetail: "./imgs/products/detail/ivy.png",
    marca: "Rumapets",
    tipo: "Rascador",
    modelo: "Ivy",
    model_image: "./imgs/products/detail/text/ivy.png",
    price: 8160,
    link: "https://www.rumapets.com.ar/rascadores-chicos/rascador-ivy",
    detail:
      "Tubo de 45cm de largo y 12cm de diámetro de madera maciza, forrado en soga de fibra natural de yute o sisal trenzado de 5 o 6mm. Alfombra de alto transito de máxima calidad de 6mm para una estética adaptable a cualquier ambiente. Forrado íntegramente en tela de polar Soft. Base de 40x40cms. Moisés/cucha superior de 40x40x13cms con almohadón reversible para mayor comodidad de nuestros peludos ante frío o calor. 2 pompones de juguete con cascabel para incentivar el instinto felino. Terminaciones redondeadas en todas las piezas para mayor seguridad y una estética agradable. Peso total aproximado: 10kg. Medidas totales aproximadas: 60x44x44cms.",
    height: "60cm",
    width: "44cm",
    depth: "44cm",
    weight: "10kg",
    material_de_tubos: "yute",
    material_de_estructura: "polar soft",
    stock: 2,

    advice:
      "Trabajamos a pedido; el tiempo de demora es de 3 semanas aproximadamente. En caso de terminar antes el producto se coordina retiro o entrega. Corroborar stock de colores y materiales. Trabajamos con mensajería privada para entregas dentro de CABA y GBA. Podes consultar costos por nuestros canales de atención. Podes retirar por Caballito en los horarios establecidos (no es local a la calle)",
  },
  {
    id: 4,
    img: "./imgs/products/atalaya.png",
    imgDetail: "./imgs/products/detail/atalaya.png",
    marca: "Rumapets",
    tipo: "Rascador",
    modelo: "Atalaya",
    model_image: "./imgs/products/detail/text/atalaya.png",
    price: 8160,
    link: "https://www.rumapets.com.ar/rascadores-medianos/rascador-atalaya",
    detail:
      "Tubo extralarge de 70x10cm de diámetro, forrado en alfombra de alto tránsito de 3mm. Cucha con entrada principal completamente forrado en tela polar Soft de 35x40x40cm. Bajo nivel para funcionalidad de descanso exterior sobre cucha, con almohadón reversible para mayor comodidad de nuestros peludos ante frío o calor. 2 pompones de juguete con cascabel para incentivar el instinto felino. Plataforma superior de 30x30cm acolchonada y forrada. Terminaciones redondeadas en todas las piezas para mayor seguridad y una estética agradable. Peso total aproximado: 11kg. Medidas totales aproximadas: 55x40x40cms.",
    height: "75cm",
    width: "55cm",
    depth: "55cm",
    weight: "11kg",
    material_de_tubos: "alfombra",
    material_de_estructura: "polar soft",
    stock: 7,
    advice:
      "Trabajamos a pedido; el tiempo de demora es de 3 semanas aproximadamente. En caso de terminar antes el producto se coordina retiro o entrega. Corroborar stock de colores y materiales. Trabajamos con mensajería privada para entregas dentro de CABA y GBA. Podes consultar costos por nuestros canales de atención. Podes retirar por Caballito en los horarios establecidos (no es local a la calle)",
  },
  {
    id: 5,
    img: "./imgs/products/nuagealfombra.png",
    imgDetail: "./imgs/products/detail/nuagealfombra.png",
    marca: "Rumapets",
    tipo: "Rascador",
    modelo: "Nuage Alfombra",
    model_image: "./imgs/products/detail/text/nuagealfombra.png",
    price: 11040,
    link: "https://www.rumapets.com.ar/rascadores-medianos/rascador-nuage-alfombra",
    detail:
      "2 tubos de 25cm y 50cm de largo de madera maciza x 10cm y 12cm de diámetro, forrado en alfombra de alto tránsito de 3mm. Forrado íntegramente en tela de Corderito o Polar Soft por fuera y dentro de los habitáculos. Cucha inferior de 40x40x35cms con entrada delantera. Moisés superior de 40x40x13cms. 1 almohadón para cada habitáculo reversibles para mayor comodidad de nuestros peludos ante frío o calor. 2 pompones de juguete con cascabel para incentivar el instinto felino. Terminaciones redondeadas en todas las piezas para mayor seguridad y una estética agradable. Peso total aproximado: 15kg. Medidas totales aproximadas: 100x60x55cms",
    height: "100cm",
    width: "60cm",
    depth: "55cm",
    weight: "15kg",
    material_de_tubos: "alfombra",
    material_de_estructura: "polar soft",
    stock: 10,
    advice:
      "Trabajamos a pedido; el tiempo de demora es de 3 semanas aproximadamente. En caso de terminar antes el producto se coordina retiro o entrega. Corroborar stock de colores y materiales. Trabajamos con mensajería privada para entregas dentro de CABA y GBA. Podes consultar costos por nuestros canales de atención. Podes retirar por Caballito en los horarios establecidos (no es local a la calle)",
  },
  {
    id: 6,
    img: "./imgs/products/nuage.png",
    imgDetail: "./imgs/products/detail/nuage.png",
    marca: "Rumapets",
    tipo: "Rascador",
    modelo: "Nuage Yute",
    model_image: "./imgs/products/detail/text/nuage.png",
    price: 14160,
    link: "https://www.rumapets.com.ar/rascadores-medianos/rascador-nuage-yute",
    detail:
      "2 tubos de 25cm y 50cm de largo de madera maciza x 10cm y 12cm de diámetro, forrado en soga de fibra natural de yute o sisal trenzado de 5 o 6mm. Forrado íntegramente en tela de corderito o polar soft por fuera y dentro de los habitáculos. Cucha inferior de 40x40x35cms con entrada delantera. Moisés superior de 40x40x13cms. 1 almohadón para cada habitáculo reversibles para mayor comodidad de nuestros peludos ante frío o calor. 2 pompones de juguete con cascabel para incentivar el instinto felino. Terminaciones redondeadas en todas las piezas para mayor seguridad y una estética agradable. Peso total aproximado: 19kg. Medidas totales aproximadas: 100x60x55cms.",
    height: "100cm",
    width: "60cm",
    depth: "55cm",
    weight: "19kg",
    material_de_tubos: "yute",
    material_de_estructura: "polar soft",
    stock: 10,
    advice:
      "Trabajamos a pedido; el tiempo de demora es de 3 semanas aproximadamente. En caso de terminar antes el producto se coordina retiro o entrega. Corroborar stock de colores y materiales. Trabajamos con mensajería privada para entregas dentro de CABA y GBA. Podes consultar costos por nuestros canales de atención. Podes retirar por Caballito en los horarios establecidos (no es local a la calle)",
  },
  {
    id: 7,
    img: "./imgs/products/kamui.png",
    imgDetail: "./imgs/products/detail/kamui.png",
    marca: "Rumapets",
    tipo: "Rascador",
    modelo: "Kamui",
    model_image: "./imgs/products/detail/text/kamui.png",
    price: 17400,
    link: "https://www.rumapets.com.ar/rascadores-medianos/rascador-kamui",
    detail:
      "4 tubos de 25cm de largo y 10cm de diámetro, forrado en soga de fibra natural de yute o sisal trenzado de 5 o 6mm. Alfombra de alto transito de 6mm para una estética adaptable a cualquier ambiente. Forrado íntegramente en tela polar Soft por fuera y dentro de los habitáculos. Cucha inferior con entrada superior de 40x40x35cms. Moisés superior de 40x40x25cms. Almohadones reversibles para mayor comodidad de nuestros peludos ante frío o calor en todos los habitáculos. 2 pompones de juguete con cascabel para incentivar el instinto felino. Terminaciones redondeadas en todas las piezas para mayor seguridad y una estética agradable. Peso total aproximado: 16kg. Medidas totales aproximadas: 90x50x55cms.",
    height: "90cm",
    width: "50cm",
    depth: "55cm",
    weight: "16kg",
    material_de_tubos: "yute",
    material_de_estructura: "polar soft",
    stock: 10,
    advice:
      "Trabajamos a pedido; el tiempo de demora es de 3 semanas aproximadamente. En caso de terminar antes el producto se coordina retiro o entrega. Corroborar stock de colores y materiales. Trabajamos con mensajería privada para entregas dentro de CABA y GBA. Podes consultar costos por nuestros canales de atención. Podes retirar por Caballito en los horarios establecidos (no es local a la calle)",
  },
  {
    id: 8,
    img: "./imgs/products/ruma.png",
    imgDetail: "./imgs/products/detail/ruma.png",
    marca: "Rumapets",
    tipo: "Rascador",
    modelo: "Ruma",
    model_image: "./imgs/products/detail/text/ruma.png",
    price: 25200,
    link: "https://www.rumapets.com.ar/rascadores-grandes/rascador-ruma",
    detail:
      "8 tubos de 25cm de largo y 10cm de diámetro, forrado en soga de fibra natural de yute o sisal trenzado de 5 o 6mm. Alfombra de alto transito de 6mm para una estética adaptable a cualquier ambiente. Forrado íntegramente en tela de polar soft por fuera y dentro de los habitáculos. Cucha inferior con entrada superior de 40x40x35cms. Moisés superior de 40x40x25cms. Almohadones reversibles para mayor comodidad de nuestros peludos ante frío o calor en todos los habitáculos. Hamaca de descanso colgante intermedia. 3 pompones de juguete con cascabel para incentivar el instinto felino. Terminaciones redondeadas en todas las piezas para mayor seguridad y una estética agradable. Peso total aproximado: 22kg. Medidas totales aproximadas: 120x50x55cms.",
    height: "120cm",
    width: "50cm",
    depth: "55cm",
    weight: "22kg",
    material_de_tubos: "yute",
    material_de_estructura: "polar soft",
    stock: 10,
    advice:
      "Trabajamos a pedido; el tiempo de demora es de 3 semanas aproximadamente. En caso de terminar antes el producto se coordina retiro o entrega. Corroborar stock de colores y materiales. Trabajamos con mensajería privada para entregas dentro de CABA y GBA. Podes consultar costos por nuestros canales de atención. Podes retirar por Caballito en los horarios establecidos (no es local a la calle)",
  },
];

module.exports = {
  products,
};
